### ISSUE TITLE
Transforming text

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/braille-css-spec#12]
Add a section describing how the transformation from text to braille can be controlled. 

See http://snaekobbi.github.io/braille-css-spec/#h3_transforming-text.

**Comment by bertfrees** [comment]
This could be accomplished with a new 'text-transform' property. The initial value would ‘auto’, meaning "it's up to the UA".

|             |                                            |
| ----------- | ------------------------------------       |
| __Name__       | text-transform                             |
| __Value__      | &lt;ident-list&gt; &#124; auto &#124; none |
| __Initial__    | auto                                       |
| __Inherited__   | no                                         |
| __Applies to__ | all elements                               |


`<ident-list>` = [ `<custom-ident>` ]+

**Comment by dkager** [comment]
Two questions:

1. Why is BrailleCSSDeclarationTransformer overriding a bunch of methods from the class it extends without changing the functionality? Example: processTextIndent().
2. What values did you come up with for TextTransform? It currently accepts an arbitrary list of values. I think this should be limited to {none, auto, uppercase, lowercase} for now. I think arbitrary values shouldn't be allowed at all (or what is a counter-example?).

Also, text-transform should probably be inherited. If I have `<p><span>Some</span> text</p>` I'd like to just say `p { text-transform: lowercase; }`

**Comment by bertfrees** [comment]
I wanted this property to be something generic with which you can precisely configure your (possibly custom) translator. The possible use cases of this property are endless, hence the arbitrary list of values. Rather than limiting the list of possible values and adding values as they are needed, I thought I'd allow everything and document new values somewhere as they are "standardized".

The rationale for this approach is that specifying the possible values and their meaning is not in the scope of Braille CSS because it can be so language and use case specific. Secondly: exactly specifying the behavior of values is not possible anyway and therefore doesn't fit so well with the rest of the spec which is in general very exact.

So maybe the definitions of values belong in some separate grammar which can possibly be overwritten or extended by other grammars?

**Comment by bertfrees** [comment]
`text-transform` is inherited, in a special way. It is already implemented, but hasn't been documented yet. Will do that shortly.

**Comment by bertfrees** [comment]
In my first comment I said:

> There are two use cases for a 'text-transform' property ...  First there is the use case of selecting a translator based on translator features. And second there is the use case of controlling the translation of text segments using text attributes.

In hindsight, trying to cover these two use cases is not such a good idea after all because it's too confusing. Translator selection should be done only once, at top-level. A translator can be made highly controllable by having it support specific values for text-transform (i.e. text attributes).

So `<query>` will not be allowed as a value, only `[ <custom-ident> ]+`.
